#!/bin/sh

. $HIPERMARK_LIB_DIR/tail/config
. $HIPERMARK_LIB_DIR/aplacc/config

NAME=$1

cp $HIPERMARK_LIB_DIR/aplacc/run run
$APLTAIL/aplt -c -O 2 -s_tail -p_tail -p_types -o $NAME.tail $APLTAIL/lib/prelude.apl $HIPERMARK_IMPLEMENTATION/../tail/$NAME.apl
aplacc -t $APLACC_OPT $NAME.tail > $NAME.hs
ghc -O3 -threaded $NAME.hs -o main
