#!/bin/sh

OUTPUT=$(./main)

echo "$OUTPUT" | grep AVGTIMING | cut -c 12- | xargs printf "%.0f" > runtime.txt
# Read result from string like "RESULT: Array (Z) [0.358351852178962]"
echo "$OUTPUT" | grep -oP '(?<=RESULT: Array \(Z\) \[)([0-9]+(\.[0-9]+)?)(?=\])' > result.json
echo "$OUTPUT"


